// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketDesk.DAL;
using TicketDesk.Domain.Entities;
using TicketDesk.Domain.Enums;

#nullable disable

namespace TicketDesk.DAL.Migrations
{
    [DbContext(typeof(TicketDeskDbContext))]
    partial class TicketDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketDesk.Domain.Entities.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.ToTable("Categories");

                b.HasData(
                    new { Id = 1, Name = "Hardware" },
                    new { Id = 2, Name = "Software" },
                    new { Id = 3, Name = "Network" },
                    new { Id = 4, Name = "Account" });
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");
                b.ToTable("Roles");

                b.HasData(
                    new { Id = 1, Name = "Admin" },
                    new { Id = 2, Name = "Agent" },
                    new { Id = 3, Name = "Customer" });
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Ticket", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasConversion<string>()
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Tickets");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.TicketComment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Body")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("TicketId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("TicketId");
                b.HasIndex("UserId");
                b.ToTable("TicketComments");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("RoleId");
                b.ToTable("Users");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Ticket", b =>
            {
                b.HasOne("TicketDesk.Domain.Entities.User", "User")
                    .WithMany("Tickets")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.TicketComment", b =>
            {
                b.HasOne("TicketDesk.Domain.Entities.Ticket", "Ticket")
                    .WithMany("Comments")
                    .HasForeignKey("TicketId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("TicketDesk.Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Ticket");
                b.Navigation("User");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.User", b =>
            {
                b.HasOne("TicketDesk.Domain.Entities.Role", "Role")
                    .WithMany("Users")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Role");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Ticket", b =>
            {
                b.HasMany("TicketDesk.Domain.Entities.Category", "Categories")
                    .WithMany("Tickets")
                    .UsingEntity<Dictionary<string, object>>(
                        "TicketCategories",
                        r => r.HasOne("TicketDesk.Domain.Entities.Category", "Category")
                            .WithMany()
                            .HasForeignKey("CategoryId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired(),
                        l => l.HasOne("TicketDesk.Domain.Entities.Ticket", "Ticket")
                            .WithMany()
                            .HasForeignKey("TicketId")
                            .OnDelete(DeleteBehavior.Cascade)
                            .IsRequired(),
                        j =>
                        {
                            j.HasKey("TicketId", "CategoryId");
                            j.HasIndex("CategoryId");
                            j.ToTable("TicketCategories");
                            j.IndexerProperty<int>("TicketId").HasColumnType("int");
                            j.IndexerProperty<int>("CategoryId").HasColumnType("int");
                        });
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Category", b =>
            {
                b.Navigation("Tickets");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Role", b =>
            {
                b.Navigation("Users");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.Ticket", b =>
            {
                b.Navigation("Categories");
                b.Navigation("Comments");
            });

            modelBuilder.Entity("TicketDesk.Domain.Entities.User", b =>
            {
                b.Navigation("Tickets");
            });
#pragma warning restore 612, 618
        }
    }
}
